#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    pos,neg,zero=0,0,0
    l=len(arr)
    for i in range(l):
        if(arr[i]>0):
            pos+=1
        elif(arr[i]==0):
            zero+=1
        else:
            neg+=1
    print(round(pos/l,6))
    print(round(neg/l,6))
    print(round(zero/l,6))    

if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
