#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    # BASIC APPROACH
    # for i in range(n):
    #     if i>0:
    #           print("")
    #         #    print("")
    #     for j in range(n):
    #             print("#",end="") if i+j>=n-1 else print(" ",end="")

                #BETTER APPROACH 
        for i in range(1, n + 1):
             print(' ' * (n - i) + '#' * i)
if __name__ == '__main__':
    n = int(input())

    staircase(n)
